const API = window.COCHECIERTO_API || ((window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') ? 'http://localhost:3000' : 'https://api.cochecierto.com');
const locked = document.querySelector('#locked');
const app = document.querySelector('#app');
const message = document.querySelector('#message');
const accessMessage = document.querySelector('#access-message');
const savedTheme = localStorage.getItem('cc_crm_theme') || (window.matchMedia?.('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
document.documentElement.dataset.theme = savedTheme;
const themeToggles = document.querySelectorAll('#theme-toggle,#theme-toggle-auth');
const updateThemeButton = () => { const dark = document.documentElement.dataset.theme === 'dark'; themeToggles.forEach((button) => { button.innerHTML = `${dark ? '☀' : '☾'} <span>${dark ? 'Modo claro' : 'Modo oscuro'}</span>`; button.setAttribute('aria-label', dark ? 'Cambiar a modo claro' : 'Cambiar a modo oscuro'); }); };
updateThemeButton();
themeToggles.forEach((button) => button.addEventListener('click', () => { const next = document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'; document.documentElement.dataset.theme = next; localStorage.setItem('cc_crm_theme', next); updateThemeButton(); }));

const transitions = {
  visitor: ['diagnostic_started', 'withdrawn', 'blocked'], diagnostic_started: ['report_requested', 'withdrawn', 'blocked'],
  report_requested: ['report_verified', 'withdrawn', 'blocked'], report_verified: ['request_draft', 'withdrawn', 'blocked'],
  request_draft: ['request_active', 'withdrawn', 'blocked'], request_active: ['shared_manual', 'withdrawn', 'blocked'],
  shared_manual: ['offer_received', 'withdrawn', 'blocked'], offer_received: ['comparison', 'withdrawn', 'blocked'],
  comparison: ['contact_authorized', 'withdrawn', 'blocked'], contact_authorized: ['visit_requested', 'withdrawn', 'blocked'],
  visit_requested: ['test_requested', 'purchased', 'withdrawn', 'blocked'], test_requested: ['purchased', 'withdrawn', 'blocked'],
  purchased: ['aftercare', 'closed', 'blocked'], aftercare: ['closed', 'blocked']
};

const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character]));
const token = () => (document.querySelector('#token')?.value || '').trim();
const headers = () => {
  const user = document.querySelector('#user') || document.querySelector('#credential');
  const email = document.querySelector('#email');
  return {
    'Content-Type': 'application/json',
    ...(user?.value?.trim() ? { 'X-CRM-User': user.value.trim() } : {}),
    ...(email?.value?.trim() ? { 'X-CRM-Email': email.value.trim() } : {})
  };
};
const api = async (path, options = {}) => {
  const response = await fetch(`${API}${path}`, { credentials: 'include', ...options, headers: { ...headers(), ...(options.headers || {}) } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.message || 'No se ha podido completar la operación.');
  return data;
};

function mountControls() {
  if (document.querySelector('#case-form')) return;
  const dealerPanel = document.querySelector('#dealer-form').closest('.panel');
  const casePanel = document.createElement('section'); casePanel.className = 'panel';
  casePanel.innerHTML = '<h2>Abrir caso interno</h2><p class="muted">Usa identificadores internos ya autorizados; no copies datos personales en notas.</p><form id="case-form"><input name="leadId" inputmode="numeric" placeholder="ID de lead (opcional)"><input name="purchaseRequestId" inputmode="numeric" placeholder="ID de petición (opcional)"><select name="stage"><option value="visitor">Visitante</option><option value="diagnostic_started">Diagnóstico iniciado</option><option value="report_requested">Informe solicitado</option></select><button>Crear caso</button></form>';
  dealerPanel.before(casePanel);
  const taskPanel = document.createElement('section'); taskPanel.className = 'panel';
  taskPanel.innerHTML = '<h2>Programar tarea de acompañamiento</h2><p class="muted">Incluye entrega y servicios posteriores sin iniciar comunicaciones automáticas.</p><form id="task-form"><input name="caseId" required inputmode="numeric" placeholder="ID del caso"><select name="taskType"><option value="documentation">Documentación</option><option value="inspection">Inspección</option><option value="insurance">Seguro</option><option value="transfer">Transferencia</option><option value="delivery">Entrega</option><option value="finance_review">Revisión financiera</option><option value="maintenance">Mantenimiento inicial</option><option value="first_service">Primera revisión</option><option value="warranty">Garantía</option><option value="warranty_claim">Reclamación de garantía</option><option value="followup">Seguimiento</option></select><input name="dueAt" type="datetime-local"><input name="notes" maxlength="500" placeholder="Nota operativa sin datos personales"><button>Crear tarea</button></form>';
  dealerPanel.after(taskPanel);
  const detailPanel = document.createElement('section'); detailPanel.className = 'panel';
  detailPanel.innerHTML = '<h2>Ver trazabilidad de un caso</h2><form id="detail-form"><input name="caseId" required inputmode="numeric" placeholder="ID del caso"><button>Consultar detalle</button></form><div id="case-detail" class="empty">Selecciona un caso para consultar sus eventos, concesionarios asociados y tareas.</div>';
  taskPanel.after(detailPanel);
  const linkPanel = document.createElement('section'); linkPanel.className = 'panel';
  linkPanel.innerHTML = '<h2>Asociar concesionario a un caso</h2><p class="muted">Relaciona un caso con un concesionario registrado sin copiar contactos en el expediente.</p><form id="link-form"><input name="caseId" required inputmode="numeric" placeholder="ID del caso"><input name="dealerId" required inputmode="numeric" placeholder="ID del concesionario"><select name="relationshipState"><option value="candidate">Candidato</option><option value="invited">Invitado</option><option value="responded">Respondió</option><option value="selected">Seleccionado</option><option value="declined">Declinó</option><option value="blocked">Bloqueado</option></select><button>Guardar asociación</button></form>';
  detailPanel.after(linkPanel);
  document.querySelector('#case-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const result = await api('/api/crm/cases', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); message.textContent = `Caso #${result.caseId} creado.`; event.currentTarget.reset(); await load(); } catch (error) { message.textContent = error.message; } });
  document.querySelector('#task-form').addEventListener('submit', async (event) => { event.preventDefault(); const body = Object.fromEntries(new FormData(event.currentTarget)); try { const result = await api(`/api/crm/cases/${encodeURIComponent(body.caseId)}/aftercare`, { method: 'POST', body: JSON.stringify(body) }); message.textContent = `Tarea #${result.taskId} creada.`; event.currentTarget.reset(); await load(); } catch (error) { message.textContent = error.message; } });
  document.querySelector('#detail-form').addEventListener('submit', async (event) => { event.preventDefault(); const body = Object.fromEntries(new FormData(event.currentTarget)); const target = document.querySelector('#case-detail'); target.textContent = 'Consultando…'; try { const result = await api(`/api/crm/cases/${encodeURIComponent(body.caseId)}`); const item = result.case; target.innerHTML = `<h3>Caso #${item.id} · ${escapeHtml(item.stage)}</h3><p>Origen: ${escapeHtml(item.source)} · Prioridad: ${escapeHtml(item.priority)} · Responsable: ${escapeHtml(item.assignedTo || 'sin asignar')}</p><h4>Eventos</h4>${result.events.length ? `<ul>${result.events.map((event) => `<li>${new Date(event.createdAt).toLocaleString('es-ES')} · ${escapeHtml(event.fromStage || 'inicio')} → ${escapeHtml(event.toStage)} · ${escapeHtml(event.reason || 'sin motivo')}</li>`).join('')}</ul>` : '<p>Sin eventos.</p>'}<h4>Concesionarios asociados</h4>${result.dealers.length ? `<ul>${result.dealers.map((dealer) => `<li>${escapeHtml(dealer.tradeName || dealer.legalName)} · ${escapeHtml(dealer.relationshipState)}</li>`).join('')}</ul>` : '<p>Ninguno.</p>'}<h4>Tareas</h4>${result.tasks.length ? `<ul>${result.tasks.map((task) => `<li>${escapeHtml(task.taskType)} · ${escapeHtml(task.status)}${task.dueAt ? ` · ${new Date(task.dueAt).toLocaleString('es-ES')}` : ''}</li>`).join('')}</ul>` : '<p>Sin tareas.</p>'}`; } catch (error) { target.textContent = error.message; } });
  document.querySelector('#link-form').addEventListener('submit', async (event) => { event.preventDefault(); const body = Object.fromEntries(new FormData(event.currentTarget)); try { const result = await api(`/api/crm/cases/${encodeURIComponent(body.caseId)}/dealers`, { method: 'POST', body: JSON.stringify(body) }); message.textContent = `Asociación caso #${result.caseId} · concesionario #${result.dealerId} guardada.`; event.currentTarget.reset(); } catch (error) { message.textContent = error.message; } });
}

function mountCaseMetadata() {
  const form = document.querySelector('#case-form'); if (!form || form.querySelector('[name="priority"]')) return;
  const priority = document.createElement('select'); priority.name = 'priority'; priority.innerHTML = '<option value="normal">Prioridad normal</option><option value="high">Prioridad alta</option><option value="low">Prioridad baja</option>';
  const assignee = document.createElement('input'); assignee.name = 'assignedTo'; assignee.placeholder = 'Responsable interno';
  const nextAction = document.createElement('input'); nextAction.name = 'nextActionAt'; nextAction.type = 'datetime-local';
  form.insertBefore(assignee, form.lastElementChild); form.insertBefore(priority, form.lastElementChild); form.insertBefore(nextAction, form.lastElementChild);
}

const planDefaults = [0,0,500,1000,1600,2400,3300,4200,5200,6300,7500,9000];
const planCosts = [1150,1050,1150,1350,1400,1500,1700,1800,1900,2000,2100,2300];
const planMonths = ['Sep','Oct','Nov','Dic','Ene','Feb','Mar','Abr','May','Jun','Jul','Ago'];
function renderPlan() {
  const saved = JSON.parse(localStorage.getItem('cc_crm_plan') || 'null') || planDefaults.map((income, i) => ({ income, costs: planCosts[i], partners: i < 2 ? 10 + i * 3 : Math.min(50, 13 + (i - 2) * 4), opportunities: i < 2 ? 0 : 5 + (i - 2) * 3 }));
  const body = document.querySelector('#plan-table-body'); if (!body) return;
  body.innerHTML = saved.map((row, i) => `<tr><th scope="row">M${i + 1} · ${planMonths[i]}</th><td><input data-plan="income" data-index="${i}" type="number" min="0" step="50" value="${row.income}"></td><td><input data-plan="costs" data-index="${i}" type="number" min="0" step="50" value="${row.costs}"></td><td><input data-plan="partners" data-index="${i}" type="number" min="0" value="${row.partners}"></td><td><input data-plan="opportunities" data-index="${i}" type="number" min="0" value="${row.opportunities}"></td><td class="plan-result">${Number(row.income) - Number(row.costs)} €</td></tr>`).join('');
  const totalIncome = saved.reduce((n, r) => n + Number(r.income || 0), 0), totalCosts = saved.reduce((n, r) => n + Number(r.costs || 0), 0);
  document.querySelector('#plan-summary').innerHTML = `<div><small>Ingresos objetivo</small><strong>${totalIncome.toLocaleString('es-ES')} €</strong></div><div><small>Costes objetivo</small><strong>${totalCosts.toLocaleString('es-ES')} €</strong></div><div><small>Resultado objetivo</small><strong>${(totalIncome - totalCosts).toLocaleString('es-ES')} €</strong></div>`;
}
function savePlan() { const rows = [...document.querySelectorAll('#plan-table-body tr')].map((row) => { const get = (name) => row.querySelector(`[data-plan="${name}"]`)?.value || ''; return { income: get('income'), costs: get('costs'), partners: get('partners'), opportunities: get('opportunities') }; }); localStorage.setItem('cc_crm_plan', JSON.stringify(rows)); renderPlan(); message.textContent = 'Versión del plan guardada en este navegador.'; }
function renderAccounting() { const items = JSON.parse(localStorage.getItem('cc_crm_accounting') || '[]'); const income = items.filter((i) => i.type === 'income').reduce((n, i) => n + Number(i.amount), 0), expense = items.filter((i) => i.type === 'expense').reduce((n, i) => n + Number(i.amount), 0); document.querySelector('#accounting-summary').innerHTML = `<div><small>Ingresos</small><strong>${income.toLocaleString('es-ES')} €</strong></div><div><small>Gastos</small><strong>${expense.toLocaleString('es-ES')} €</strong></div><div><small>Resultado</small><strong>${(income - expense).toLocaleString('es-ES')} €</strong></div>`; document.querySelector('#accounting-list').innerHTML = items.length ? `<div class="data-table"><div class="data-table-row data-table-head"><span>Fecha</span><span>Concepto</span><span>Tipo</span><span>Importe</span><span></span></div>${items.map((item, i) => `<div class="data-table-row"><span>${escapeHtml(item.date)}</span><span>${escapeHtml(item.description)}<small>${escapeHtml(item.category)}</small></span><span>${item.type === 'income' ? 'Ingreso' : 'Gasto'}</span><strong>${Number(item.amount).toLocaleString('es-ES')} €</strong><button class="icon-button" data-accounting-delete="${i}" type="button" aria-label="Eliminar movimiento">×</button></div>`).join('')}</div>` : '<p class="muted">Todavía no hay movimientos.</p>'; document.querySelectorAll('[data-accounting-delete]').forEach((b) => b.addEventListener('click', () => { const next = items.filter((_, i) => i !== Number(b.dataset.accountingDelete)); localStorage.setItem('cc_crm_accounting', JSON.stringify(next)); renderAccounting(); })); }
function mountBusinessTools() { renderPlan(); renderAccounting(); document.querySelector('#plan-save')?.addEventListener('click', savePlan); document.querySelector('#accounting-form')?.addEventListener('submit', (e) => { e.preventDefault(); const item = Object.fromEntries(new FormData(e.currentTarget)); const items = JSON.parse(localStorage.getItem('cc_crm_accounting') || '[]'); items.unshift(item); localStorage.setItem('cc_crm_accounting', JSON.stringify(items)); e.currentTarget.reset(); renderAccounting(); }); document.querySelector('#accounting-clear')?.addEventListener('click', () => { localStorage.removeItem('cc_crm_accounting'); renderAccounting(); }); }
function applyView(view) { const target = view === 'ads' ? 'traffic' : (view || 'dashboard'); document.querySelectorAll('[data-view-section]').forEach((section) => { section.hidden = section.dataset.viewSection !== target; }); document.querySelectorAll('[data-view]').forEach((link) => link.classList.toggle('active', link.dataset.view === target || (target === 'traffic' && link.dataset.view === 'traffic'))); const dashboardHeader = document.querySelector('#dashboard'); if (dashboardHeader) dashboardHeader.hidden = target !== 'dashboard'; const dynamic = { opportunities: ['#case-form','#case-detail','#link-form','#case-list'], partners: ['#dealer-form','#dealer-list'], tasks: ['#task-form','#task-list'], analytics: ['.insights-grid'], traffic: ['.traffic-panel'], voice: ['.voice-panel'], assistant: ['#assistant-feedback-panel'], alerts: ['#observability-panel'] }; document.querySelectorAll('#app > .panel:not([data-view-section]),#app > .decision-grid:not([data-view-section])').forEach((el) => { if (target === 'dashboard') el.hidden = true; }); (dynamic[target] || []).forEach((selector) => { const el = document.querySelector(selector); if (el) (el.closest('.panel') || el).hidden = false; }); if (target === 'dashboard') document.querySelectorAll('[data-view-section="dashboard"]').forEach((el) => { el.hidden = false; }); }
function mountNavigation() { document.querySelectorAll('[data-view]').forEach((link) => link.addEventListener('click', (event) => { event.preventDefault(); const view = link.dataset.view; history.replaceState(null, '', `#${link.getAttribute('href').slice(1)}`); applyView(view); })); const initial = location.hash === '#voice' ? 'voice' : location.hash === '#accounting' ? 'accounting' : location.hash === '#business-plan' ? 'business-plan' : location.hash === '#analytics' ? 'analytics' : (location.hash === '#ads' || location.hash === '#traffic') ? 'traffic' : location.hash === '#assistant' ? 'assistant' : location.hash === '#alerts' ? 'alerts' : location.hash === '#opportunities' ? 'opportunities' : location.hash === '#partners' ? 'partners' : location.hash === '#tasks' ? 'tasks' : 'dashboard'; applyView(initial); }

function renderVoice(data) { const metrics = data.metrics || {}; const target = document.querySelector('#voice-metrics'); const list = document.querySelector('#voice-leads'); if (!target || !list) return; target.innerHTML = [['Leads', metrics.leads], ['Emails enviados', metrics.emailsSent], ['Validados', metrics.validated], ['PDF descargado', metrics.pdfDownloaded], ['Caducados', metrics.expired], ['Fallos', metrics.failed]].map(([label, value]) => `<article class="metric"><small>${escapeHtml(label)}</small><strong>${escapeHtml(value ?? '—')}</strong></article>`).join(''); list.innerHTML = data.leads?.length ? `<div class="data-table"><div class="data-table-row voice-table-head"><span>ID</span><span>Lead</span><span>Estado</span><span>Actividad</span></div>${data.leads.map((lead) => `<div class="data-table-row voice-table-row"><span>#${escapeHtml(lead.id)}</span><span><strong>${escapeHtml(lead.name)}</strong><small>${escapeHtml(lead.email)}</small></span><span>${escapeHtml(lead.state)}</span><span>${lead.lastActivity ? new Date(lead.lastActivity).toLocaleString('es-ES') : '—'}</span></div>`).join('')}</div>` : '<p class="muted">No hay leads en el periodo seleccionado.</p>'; }
function renderNewsletter(data) { const target = document.querySelector('#newsletter-metrics'); const state = document.querySelector('#newsletter-state'); if (!target || !state) return; state.textContent = data.active ? 'Activa' : 'No activa'; state.className = `source-state${data.active ? '' : ' source-state--off'}`; const m = data.metrics || {}; target.innerHTML = [['Suscriptores con opt-in', m.optedIn], ['Nuevas altas', m.newSignups], ['Pendientes', m.pending], ['En pausa', m.paused], ['Bajas', m.unsubscribed], ['Entrega', m.deliveryRate == null ? '—' : `${m.deliveryRate}%`]].map(([label, value]) => `<article class="metric"><small>${escapeHtml(label)}</small><strong>${escapeHtml(value ?? '—')}</strong></article>`).join(''); }

function renderAds(data, metrics) { const state = document.querySelector('#ads-source-state'), status = document.querySelector('#ads-status'), metricTarget = document.querySelector('#ads-metrics'); if (!state || !status || !metricTarget) return; const labels = { disabled: 'Desactivado', not_configured: 'Sin configurar', ready: 'Conectado', error: 'Error' }; state.textContent = labels[data.status] || 'Sin estado'; state.className = `source-state${data.status === 'ready' ? '' : ' source-state--off'}`; status.innerHTML = `<div class="integration-mark integration-mark--meta">f</div><div><strong>${escapeHtml(data.message)}</strong><p class="muted">${escapeHtml(data.detail)}</p></div>`; const values = data.metrics || {}; metricTarget.innerHTML = [['Impresiones', values.impressions], ['Clics', values.clicks], ['Gasto', values.spend], ['Conversiones', values.conversions]].map(([label, value]) => `<article class="metric"><small>${label}</small><strong>${value == null ? '—' : escapeHtml(value)}</strong></article>`).join('') + `<div class="ads-owned"><small>Leads atribuidos propios · ${escapeHtml(metrics.period.days)} días</small><strong>${escapeHtml(metrics.attribution?.facebook || 0)}</strong></div>`; }
function renderExitFeedback(data) { const target = document.querySelector('#exit-feedback-panel'); if (!target) return; const labels = { helpful: 'Sí, me ha ayudado', uncertain: 'Tengo algunas dudas', not_yet: 'Todavía no' }; target.innerHTML = data.rows?.length ? data.rows.map((row) => `<div class="data-list-row"><span>${escapeHtml(labels[row.usefulness] || row.usefulness)}</span><strong>${escapeHtml(row.total)}</strong></div>`).join('') : '<p class="muted">Aún no hay respuestas en este periodo.</p>'; const assistant = document.querySelector('#assistant-feedback-panel'); if (assistant) assistant.innerHTML = data.rows?.length ? data.rows.map((row) => `<div class="data-list-row"><span>${escapeHtml(({ helpful: 'Clara ayudó a entender el siguiente paso', uncertain: 'Clara debe explicar mejor', not_yet: 'El usuario aún no encontró valor' })[row.usefulness] || row.usefulness)}</span><strong>${escapeHtml(row.total)}</strong></div>`).join('') + '<p class="definition">Las respuestas se agrupan para orientar mejoras de onboarding.</p>' : '<p class="muted">Aún no hay opiniones de Clara en este periodo.</p>'; }

async function updateDealerStatus(dealerId, status, dataProcessingStatus) {
  try { await api(`/api/crm/dealers/${dealerId}/status`, { method: 'POST', body: JSON.stringify({ status, dataProcessingStatus, verificationStatus: status === 'verified' ? 'approved' : 'pending_review' }) }); message.textContent = `Estado del concesionario #${dealerId} actualizado.`; await load(); } catch (error) { message.textContent = error.message; }
}

async function showDealerContacts(dealerId, target) {
  target.textContent = 'Consultando contactos…';
  try {
    const result = await api(`/api/crm/dealers/${dealerId}/contacts`);
    target.innerHTML = result.contacts.length ? result.contacts.map((contact) => `<div class="contact"><strong>${escapeHtml(contact.contactName)}</strong><span>${escapeHtml(contact.role || 'Sin cargo')} · ${escapeHtml(contact.preferredChannel || 'Canal pendiente')}</span><small>${escapeHtml(contact.email || 'Sin email')} · ${escapeHtml(contact.phone || contact.whatsapp || 'Sin teléfono')}</small><label>Autorización <select class="contact-status" data-dealer-id="${dealerId}" data-contact-id="${contact.id}"><option value="pending_review" ${contact.consentStatus === 'pending_review' ? 'selected' : ''}>Pendiente</option><option value="approved" ${contact.consentStatus === 'approved' ? 'selected' : ''}>Aprobado</option><option value="rejected" ${contact.consentStatus === 'rejected' ? 'selected' : ''}>Rechazado</option></select></label></div>`).join('') : 'Sin contactos activos.';
    target.querySelectorAll('.contact-status').forEach((select) => select.addEventListener('change', async () => { try { await api(`/api/crm/dealers/${select.dataset.dealerId}/contacts/${select.dataset.contactId}/status`, { method: 'POST', body: JSON.stringify({ consentStatus: select.value }) }); message.textContent = 'Autorización del contacto actualizada.'; } catch (error) { message.textContent = error.message; } }));
  } catch (error) { target.textContent = error.message; }
}

function renderDealers(dealers) {
  const list = document.querySelector('#dealer-list');
  if (!list) return;
  if (!dealers.length) { list.innerHTML = 'Todavía no hay concesionarios registrados.'; return; }
  list.innerHTML = dealers.map((dealer) => `<article class="dealer-row"><div class="row"><strong>${escapeHtml(dealer.tradeName || dealer.legalName)}<br><small>${escapeHtml(dealer.legalName)}</small></strong><span>${escapeHtml(dealer.status)} · ${escapeHtml(dealer.verificationStatus)}</span></div><div class="dealer-actions"><select data-status-id="${dealer.id}"><option value="draft" ${dealer.status === 'draft' ? 'selected' : ''}>Borrador</option><option value="pending_review" ${dealer.status === 'pending_review' ? 'selected' : ''}>Pendiente de revisión</option><option value="verified" ${dealer.status === 'verified' ? 'selected' : ''}>Verificado</option><option value="suspended" ${dealer.status === 'suspended' ? 'selected' : ''}>Suspendido</option></select><select data-processing-id="${dealer.id}"><option value="pending_review" ${dealer.dataProcessingStatus !== 'approved' ? 'selected' : ''}>RGPD pendiente</option><option value="approved" ${dealer.dataProcessingStatus === 'approved' ? 'selected' : ''}>Tratamiento aprobado</option></select><button type="button" class="contacts-button" data-dealer-id="${dealer.id}">Ver contactos restringidos</button></div><div class="dealer-contacts" id="contacts-${dealer.id}" hidden></div></article>`).join('');
  list.querySelectorAll('[data-status-id]').forEach((select) => select.addEventListener('change', () => { const processing = list.querySelector(`[data-processing-id="${select.dataset.statusId}"]`)?.value || 'pending_review'; updateDealerStatus(select.dataset.statusId, select.value, processing); }));
  list.querySelectorAll('[data-processing-id]').forEach((select) => select.addEventListener('change', () => { const status = list.querySelector(`[data-status-id="${select.dataset.processingId}"]`)?.value || 'draft'; updateDealerStatus(select.dataset.processingId, status, select.value); }));
  list.querySelectorAll('.contacts-button').forEach((button) => button.addEventListener('click', () => { const target = document.querySelector(`#contacts-${button.dataset.dealerId}`); target.hidden = !target.hidden; if (!target.hidden) showDealerContacts(button.dataset.dealerId, target); }));
}

async function load() {
  message.textContent = 'Consultando…';
  try {
    const selectedDays = document.querySelector('#period')?.value || '30';
    const stageFilter = document.querySelector('#stage-filter')?.value || '', priorityFilter = document.querySelector('#priority-filter')?.value || '';
    const caseQuery = new URLSearchParams(); if (stageFilter) caseQuery.set('stage', stageFilter); if (priorityFilter) caseQuery.set('priority', priorityFilter);
    const [summary, dealers, cases, aftercare, metrics] = await Promise.all([api('/api/crm/summary'), api('/api/crm/dealers'), api(`/api/crm/cases${caseQuery.toString() ? `?${caseQuery}` : ''}`), api('/api/crm/aftercare'), api(`/api/crm/metrics?days=${encodeURIComponent(selectedDays)}`)]);
    const observability = await api('/api/crm/observability').catch(() => ({ events: { byType: {} }, alerts: [{ severity: 'warning', message: 'Instrumentación pendiente', action: 'Aplica la migración CRM 003 para activar métricas de eventos.' }], integrations: { email: 'pendiente de esquema', social: 'pendiente de esquema' } }));
    const ads = await api(`/api/crm/ads?days=${encodeURIComponent(selectedDays)}`).catch(() => ({ status: 'error', message: 'No se pudo consultar el tráfico de pago.', detail: 'Revisa el estado del conector en el servidor.', metrics: {} }));
    renderAds(ads, metrics);
    const [voice, newsletter, feedback] = await Promise.all([api(`/api/crm/voice?days=${encodeURIComponent(selectedDays)}`).catch(() => ({ metrics: {}, leads: [] })), api(`/api/crm/newsletter?days=${encodeURIComponent(selectedDays)}`).catch(() => ({ metrics: {}, active: false })), api(`/api/crm/exit-feedback?days=${encodeURIComponent(selectedDays)}`).catch(() => ({ rows: [] }))]);
    renderVoice(voice);
    renderNewsletter(newsletter);
    renderExitFeedback(feedback);
    document.querySelector('#cases').textContent = summary.cases.total || 0; document.querySelector('#dealers').textContent = dealers.dealers.length; document.querySelector('#aftercare').textContent = summary.aftercare.open || 0; document.querySelector('#overdue').textContent = summary.cases.overdue || 0;
    document.querySelector('.period-badge').textContent = `${selectedDays} días`;
    const metricItems = [['Casos activos', metrics.cases.active], ['Conversión a ganada', metrics.cases.conversionToWon == null ? '—' : `${metrics.cases.conversionToWon}%`], ['Respuesta partner', metrics.partnerFlow.responseRate == null ? '—' : `${metrics.partnerFlow.responseRate}%`], ['Consentimientos', metrics.consent.authorized || 0], ['Tareas vencidas', metrics.tasks.overdue], ['Compartidos', metrics.events.share_created || 0], ['Referidos activados', metrics.events.referred_user_activated || 0], ['MRR / SaaS', '—']];
    document.querySelector('#ceo-metrics').innerHTML = metricItems.map(([label, value]) => `<article class="metric"><small>${escapeHtml(label)}</small><strong>${escapeHtml(value)}</strong></article>`).join('');
    const funnelLabels = [['visitor', 'Visitantes'], ['diagnostic_started', 'Diagnóstico'], ['report_requested', 'Informe'], ['shared_manual', 'Compartido'], ['contact_authorized', 'Contacto'], ['visit_requested', 'Cita'], ['test_requested', 'Prueba'], ['purchased', 'Ganada']];
    const funnelMax = Math.max(1, ...funnelLabels.map(([stage]) => Number(metrics.funnel[stage] || 0)));
    document.querySelector('#funnel').innerHTML = funnelLabels.map(([stage, label]) => { const value = Number(metrics.funnel[stage] || 0); return `<div class="funnel-row"><span>${escapeHtml(label)}</span><div class="funnel-track"><i style="--funnel-height:${Math.round(value / funnelMax * 100)}%"></i></div><b>${value}</b></div>`; }).join('');
    const attributionPanel = document.querySelector('#attribution-panel');
    const attributionRows = Object.entries(metrics.attribution || {}).map(([source, total]) => `<div class="data-list-row"><span>${escapeHtml(source)}</span><strong>${total}</strong></div>`).join(''); attributionPanel.innerHTML = attributionRows || '<p class="muted">Aún no hay leads con UTMs.</p>';
    const observationTarget = document.querySelector('#observability');
    const eventRows = Object.entries(observability.events.byType || {}).map(([type, total]) => `<span class="pill">${escapeHtml(type)}: ${total}</span>`).join('');
    const alertRows = (observability.alerts || []).map((alert) => `<div class="alert ${escapeHtml(alert.severity)}"><strong>${escapeHtml(alert.message)}</strong><small>${escapeHtml(alert.action)}</small></div>`).join('');
    observationTarget.innerHTML = `${eventRows || '<p>No hay eventos en el periodo.</p>'}${alertRows || '<p class="ok">Sin alertas operativas.</p>'}<p class="muted">Email: ${escapeHtml(observability.integrations.email)} · Social: ${escapeHtml(observability.integrations.social)}</p>`;
    renderDealers(dealers.dealers);
    const stageSummary = Object.entries(summary.cases.byStage || {}).map(([stage, total]) => `<span class="pill">${escapeHtml(stage)}: ${total}</span>`).join('');
    const rows = cases.cases.map((item) => { const options = (transitions[item.stage] || []).map((stage) => `<option value="${stage}">${stage}</option>`).join(''); return `<div class="row"><strong>Caso #${item.id}<br><small>${escapeHtml(item.stage)}</small></strong><span>${new Date(item.updatedAt).toLocaleDateString('es-ES')} ${options ? `<select data-case-id="${item.id}" class="stage-select"><option value="">Avanzar fase…</option>${options}</select>` : ''}</span></div>`; }).join('');
    const caseList = document.querySelector('#case-list'); caseList.innerHTML = `${stageSummary ? `<div class="stage-summary">${stageSummary}</div>` : ''}${rows || '<div class="empty">Todavía no hay casos registrados.</div>'}`;
    let taskList = document.querySelector('#task-list'); if (!taskList) { const panel = document.createElement('section'); panel.className = 'panel'; panel.innerHTML = '<h2>Tareas abiertas</h2><div id="task-list" class="empty"></div>'; document.querySelector('#app').append(panel); taskList = document.querySelector('#task-list'); }
    taskList.innerHTML = aftercare.tasks.length ? aftercare.tasks.map((task) => `<div class="row"><strong>Caso #${task.caseId}<br><small>${escapeHtml(task.taskType)}</small></strong><span>${escapeHtml(task.stage)} · ${task.dueAt ? new Date(task.dueAt).toLocaleString('es-ES') : 'sin fecha'} <button type="button" data-task-id="${task.id}" class="complete-task">Completar</button></span></div>`).join('') : 'No hay tareas abiertas.';
    taskList.querySelectorAll('.complete-task').forEach((button) => button.addEventListener('click', async () => { try { await api(`/api/crm/aftercare/${button.dataset.taskId}/complete`, { method: 'POST' }); await load(); } catch (error) { message.textContent = error.message; } }));
    caseList.querySelectorAll('.stage-select').forEach((select) => select.addEventListener('change', async () => { if (!select.value) return; try { await api(`/api/crm/cases/${select.dataset.caseId}/events`, { method: 'POST', body: JSON.stringify({ toStage: select.value, reason: 'Actualización desde consola interna' }) }); await load(); } catch (error) { message.textContent = error.message; select.value = ''; } }));
    message.textContent = '';
  } catch (error) { message.textContent = error.message; }
}

document.querySelector('#load').addEventListener('click', load);
document.querySelector('#period').addEventListener('change', load);
document.querySelector('#stage-filter').addEventListener('change', load);
document.querySelector('#priority-filter').addEventListener('change', load);
document.querySelector('#dealer-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const result = await api('/api/crm/dealers', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); message.textContent = result.message; event.currentTarget.reset(); await load(); } catch (error) { message.textContent = error.message; } });
let challengeId = '';
document.querySelector('#access-form').addEventListener('submit', async (event) => { event.preventDefault(); const credential = document.querySelector('#credential'), credentialLabel = document.querySelector('#credential-label'), email = document.querySelector('#email').value.trim(), submit = document.querySelector('#access-submit'); accessMessage.textContent = challengeId ? 'Validando código…' : 'Solicitando código…'; try { if (!challengeId) { const response = await fetch(`${API}/api/crm/auth/request-code`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ user: credential.value.trim(), email }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || `No se pudo solicitar el código (HTTP ${response.status}).`); challengeId = data.challengeId || ''; credentialLabel.firstChild.textContent = 'Código de 6 dígitos'; credential.type = 'text'; credential.inputMode = 'numeric'; credential.autocomplete = 'one-time-code'; credential.pattern = '[0-9]{6}'; credential.maxLength = 6; credential.value = ''; credential.placeholder = '000000'; submit.firstChild.textContent = 'Acceder al panel '; accessMessage.textContent = 'Introduce el código enviado al correo autorizado.'; credential.focus(); return; } const response = await fetch(`${API}/api/crm/auth/verify-code`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'include', body: JSON.stringify({ challengeId, code: credential.value.trim() }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || `El código no es válido o ha caducado (HTTP ${response.status}).`); locked.hidden = true; app.hidden = false; mountControls(); mountCaseMetadata(); mountBusinessTools(); mountNavigation(); await load(); accessMessage.textContent = data.message || 'Sesión validada.'; } catch (error) { accessMessage.textContent = error instanceof TypeError ? 'No se pudo conectar con la API privada. Revisa que api.cochecierto.com esté disponible.' : (error.message || 'No se ha podido completar el acceso.'); } });
async function bootstrapSession() {
  app.hidden = true;
  locked.hidden = false;
  try {
    await api('/api/crm/summary');
    locked.hidden = true;
    app.hidden = false;
    mountControls();
    mountCaseMetadata();
    mountBusinessTools();
    mountNavigation();
    await load();
  } catch (_) {
    // La sesión no existe o ha caducado: se mantiene el acceso visible.
  }
}
bootstrapSession();
