(function () {
  'use strict';
  const state = document.querySelector('#requestState');
  const api = window.COCHECIERTO_API || (location.hostname.endsWith('cochecierto.com') ? 'https://api.cochecierto.com/api' : '/api');
  const token = new URLSearchParams(window.location.search).get('token');
  const labels = { area: 'Zona aproximada', radius: 'Radio de referencia', category: 'Categoría', body: 'Carrocería', usage: 'Uso principal', kilometres: 'Kilómetros', people: 'Personas habituales', budget: 'Presupuesto declarado', priority: 'Prioridad', zbe: 'ZBE o restricciones' };
  const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
  const emit = (name) => document.dispatchEvent(new CustomEvent('cochecierto:event', { detail: { name, source_page: 'private-request', version: 'p1-v1' } }));
  const message = (title, body) => { state.innerHTML = `<h2>${escapeHtml(title)}</h2><p>${escapeHtml(body)}</p>`; };
  if (!/^[a-f0-9]{64}$/i.test(token || '')) { message('Enlace no disponible', 'El enlace privado no es válido o está incompleto.'); emit('private_request_invalid'); return; }
  fetch(`${api}/purchase-requests/${encodeURIComponent(token)}`).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.message || 'unavailable'); return payload; }).then((payload) => {
    const request = payload.request || {}, profile = request.profile || {};
    const rows = [['area', request.area], ['radius', `${request.radius} km`], ...Object.keys(labels).filter((key) => key !== 'area' && key !== 'radius').map((key) => [key, profile[key]])].filter(([, value]) => value);
    state.innerHTML = `<h2>Resumen de necesidades</h2><p>Esta es la información autorizada para preparar una oferta. Los datos que no aparecen aquí permanecen ocultos.</p><dl>${rows.map(([key, value]) => `<dt>${labels[key]}</dt><dd>${escapeHtml(value)}</dd>`).join('')}</dl><div class="request-pending"><strong>Debe confirmarse:</strong> vehículo concreto, precio final, disponibilidad, garantía, historial, financiación y condiciones de prueba o inspección.</div><h2>Respuesta útil para comparar</h2><p>Si eres un vendedor, separa claramente estos elementos:</p><ul><li>Vehículo, versión, motor, kilometraje y disponibilidad.</li><li>Precio final al contado, impuestos, gastos y extras.</li><li>Financiación completa solo si se solicita: entrada, TAE, plazo, cuota y coste total.</li><li>Garantía, historial, pendientes y posibilidad de prueba o inspección.</li></ul><div class="request-actions"><button class="button secondary" id="printRequest" type="button">Imprimir o guardar como PDF</button>${payload.role === 'owner' ? '<a class="button secondary" href="../comparar-ofertas/?token=' + encodeURIComponent(token) + '">Consultar ofertas</a><button class="button secondary" id="revokeRequest" type="button">Retirar esta petición</button><button class="button secondary" id="deleteRequest" type="button">Eliminar definitivamente</button>' : ''}</div>${payload.role === 'owner' ? '<div class="owner-invite"><h2>Invitar a un concesionario</h2><p>Genera un enlace de respuesta y compártelo tú. CocheCierto no enviará mensajes.</p><label>Nombre del concesionario (opcional)<input id="dealerInviteName" maxlength="160"></label><label class="invite-consent"><input id="receiveOffersConsent" type="checkbox"> Acepto recibir una oferta de este concesionario y revisarla antes de decidir. No autorizo contacto ni comunicaciones comerciales.</label><button class="button secondary" id="createDealerInvite" type="button">Generar invitación</button><p id="inviteFeedback" class="request-note" aria-live="polite"></p></div>' : ''}`;
    emit('private_request_viewed');
    document.querySelector('#printRequest').addEventListener('click', () => { emit('private_request_print_started'); window.print(); });
    const revokeButton = document.querySelector('#revokeRequest');
    if (revokeButton) revokeButton.addEventListener('click', async () => { if (!window.confirm('¿Quieres retirar esta petición? El enlace dejará de mostrar su contenido.')) return; const response = await fetch(`${api}/purchase-requests/${encodeURIComponent(token)}/revoke`, { method: 'POST', headers: { 'Content-Type': 'application/json' } }); if (!response.ok) { message('No se ha podido retirar', 'Inténtalo de nuevo más tarde.'); return; } message('Petición retirada', 'El enlace ya no muestra la información.'); emit('private_request_revoked'); });
    const deleteButton = document.querySelector('#deleteRequest');
    if (deleteButton) deleteButton.addEventListener('click', async () => { if (!window.confirm('¿Quieres eliminar definitivamente esta petición y sus ofertas? Esta acción no se puede deshacer.')) return; const response = await fetch(`${api}/purchase-requests/${encodeURIComponent(token)}`, { method: 'DELETE' }); if (!response.ok) { message('No se ha podido eliminar', 'Inténtalo de nuevo más tarde.'); return; } message('Petición eliminada', 'La ficha y sus ofertas asociadas ya no están disponibles.'); emit('private_request_deleted'); });
    const inviteButton = document.querySelector('#createDealerInvite');
    if (inviteButton) inviteButton.addEventListener('click', async () => { const inviteFeedback = document.querySelector('#inviteFeedback'); const receiveOffers = document.querySelector('#receiveOffersConsent'); if (!receiveOffers.checked) { inviteFeedback.textContent = 'Confirma por separado que aceptas recibir una oferta de este concesionario.'; return; } inviteFeedback.textContent = 'Generando invitación…'; const dealerName = document.querySelector('#dealerInviteName').value.trim(); try { const response = await fetch(`${api}/purchase-requests/${encodeURIComponent(token)}/invitations`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ dealerName, consent: { receiveOffers: true } }) }); const invite = await response.json(); if (!response.ok) throw new Error(invite.message || 'No disponible'); inviteFeedback.innerHTML = `Invitación lista: <a href="${escapeHtml(invite.inviteUrl)}" target="_blank" rel="noopener">abrir y copiar enlace</a>.`; emit('dealer_invitation_created'); } catch (error) { inviteFeedback.textContent = error.message || 'No se ha podido generar la invitación.'; emit('dealer_invitation_creation_failed'); } });
  }).catch((error) => { message('Petición no disponible', error.message === 'unavailable' ? 'Ha caducado, se ha retirado o no está disponible.' : 'No se ha podido consultar el enlace.'); emit('private_request_unavailable'); });
})();
