(function () {
  'use strict';
  const state = document.querySelector('#compareState');
  const api = window.COCHECIERTO_API || (location.hostname.endsWith('cochecierto.com') ? 'https://api.cochecierto.com/api' : '/api');
  const token = new URLSearchParams(location.search).get('token');
  const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
  const emit = (name) => document.dispatchEvent(new CustomEvent('cochecierto:event', { detail: { name, source_page: 'offer-comparison', version: 'p3-v3' } }));
  const message = (title, body) => { state.innerHTML = `<h2>${escapeHtml(title)}</h2><p>${escapeHtml(body)}</p>`; };
  const required = ['dealerName', 'vehicle', 'version', 'condition', 'availability', 'finalCashPrice', 'priceBreakdown', 'warranty', 'testAndInspection', 'offerValidity', 'accuracyDeclaration'];
  if (!/^[a-f0-9]{64}$/i.test(token || '')) { message('Comparación no disponible', 'El enlace no es válido o está incompleto.'); emit('offer_comparison_invalid'); return; }
  fetch(`${api}/purchase-requests/${encodeURIComponent(token)}/offers`).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.message || 'unavailable'); return payload; }).then(async (payload) => {
    const allOffers = Array.isArray(payload.offers) ? payload.offers : [];
    const complete = (entry) => required.every((key) => String(entry?.offer?.[key] || '').trim());
    const offers = allOffers.filter(complete).slice(0, 3), incomplete = allOffers.filter((entry) => !complete(entry));
    if (!allOffers.length) { message('Todavía no hay ofertas', 'Cuando un concesionario responda mediante una invitación activa, sus propuestas aparecerán aquí.'); emit('offer_comparison_empty'); return; }
    const card = (entry, index, comparable) => { const offer = entry.offer || {}; const rows = [['Vendedor', offer.dealerName], ['Vehículo', offer.vehicle], ['Versión y motor', offer.version], ['Año / kilometraje', [offer.year, offer.kilometres].filter(Boolean).join(' · ')], ['Estado', offer.condition], ['Disponibilidad', offer.availability], ['Precio contado', offer.finalCashPrice], ['Desglose', offer.priceBreakdown], ['Financiación', offer.financing], ['Garantía', offer.warranty], ['Historial / estado', offer.usedHistory], ['Prueba e inspección', offer.testAndInspection], ['Entrega, reserva y devolución', offer.deliveryConditions], ['Vigencia', offer.offerValidity], ['Extras', offer.extras]]; return `<article class="offer-card${comparable ? '' : ' offer-card-incomplete'}"><h3>${comparable ? `Oferta comparable ${index + 1}` : 'Respuesta pendiente'} · versión ${escapeHtml(entry.version)}</h3><p class="offer-source">${comparable ? 'Datos aportados por el concesionario; CocheCierto no certifica la unidad.' : 'No comparable todavía: faltan campos mínimos o la declaración de exactitud.'}</p><dl>${rows.filter(([, value]) => value).map(([label, value]) => `<dt>${escapeHtml(label)}</dt><dd>${escapeHtml(value)}</dd>`).join('')}</dl><div class="offer-pending">${offer.notes ? `<strong>Pendientes o notas:</strong><br>${escapeHtml(offer.notes)}` : 'Pendientes: confirmar por escrito antes de pagar.'}</div></article>`; };
    const comparableHtml = offers.length ? `<div class="compare-grid">${offers.map((entry, index) => card(entry, index, true)).join('')}</div>` : '<div class="offer-pending">Las respuestas recibidas aún no tienen información suficiente para compararlas.</div>';
    const pendingHtml = incomplete.length ? `<h2>Respuestas pendientes (${incomplete.length})</h2><p>Requieren completar o confirmar información antes de compararse.</p><div class="compare-grid">${incomplete.slice(0, 3).map((entry, index) => card(entry, index, false)).join('')}</div>` : '';
    state.innerHTML = `<h2>${offers.length} oferta${offers.length === 1 ? '' : 's'} comparable${offers.length === 1 ? '' : 's'}</h2><p>Se muestran en orden de recepción. CocheCierto no las ordena por pago, patrocinio ni cuota mensual.</p>${comparableHtml}${pendingHtml}`;
    const tracking = await fetch(`${api}/purchase-requests/${encodeURIComponent(token)}/comparison-viewed`, { method: 'POST', headers: { 'Content-Type': 'application/json' } }).then((response) => response.json()).catch(() => ({ contactAuthorizationAvailable: false }));
    const contactAction = document.createElement('div'); contactAction.className = 'offer-pending'; contactAction.innerHTML = tracking.contactAuthorizationAvailable ? '<strong>¿Quieres que se valore un contacto?</strong><br><span>Solo registra tu autorización; CocheCierto no enviará mensajes automáticamente.</span><br><button type="button" class="button secondary" id="authorizeContact">Autorizar contacto</button><p id="contactFeedback"></p>' : '<strong>Contacto pendiente de activación</strong><br><span>Esta función se habilitará cuando el servicio esté autorizado y configurado.</span>'; state.append(contactAction);
    const authorizeButton = document.querySelector('#authorizeContact'); if (authorizeButton) authorizeButton.addEventListener('click', async () => { const feedback = document.querySelector('#contactFeedback'); if (!window.confirm('¿Autorizas que se valore un contacto sobre estas ofertas?')) return; feedback.textContent = 'Registrando autorización…'; try { const response = await fetch(`${api}/purchase-requests/${encodeURIComponent(token)}/contact-authorized`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ consent: { contact: true } }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message || 'No disponible'); feedback.textContent = result.message; } catch (error) { feedback.textContent = error.message; } });
    emit('offer_comparison_viewed');
  }).catch((error) => { message('Comparación no disponible', error.message === 'unavailable' ? 'La petición ha caducado, se ha retirado o no está disponible.' : 'No se han podido consultar las ofertas.'); emit('offer_comparison_unavailable'); });
})();
